# this notebook includes the implementation of knn imputer  to handle missing values.
It is highly preferred method of multivariate imputation, where we consider other columns to fill missing values in a column.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from  sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer,KNNImputer

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("titanic_full.csv")[['Age','Pclass','Fare','Survived']]
df

      Age  Pclass     Fare  Survived
0    22.0       3   7.2500         0
1    38.0       1  71.2833         1
2    26.0       3   7.9250         1
3    35.0       1  53.1000         1
4    35.0       3   8.0500         0
..    ...     ...      ...       ...
886  27.0       2  13.0000         0
887  19.0       1  30.0000         1
888   NaN       3  23.4500         0
889  26.0       1  30.0000         1
890  32.0       3   7.7500         0

[891 rows x 4 columns]

In [3]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [4]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=12)

In [6]:
X_train

      Age  Pclass      Fare
8    27.0       3   11.1333
150  51.0       2   12.5250
221  27.0       2   13.0000
365  30.0       3    7.2500
324   NaN       3   69.5500
..    ...     ...       ...
241   NaN       3   15.5000
253  30.0       3   16.1000
390  36.0       1  120.0000
667   NaN       3    7.7750
843  34.5       3    6.4375

[712 rows x 3 columns]

In [7]:
si = SimpleImputer()
X_train_imputed = si.fit_transform(X_train)
X_test_imputed = si.transform(X_test)

lr = LogisticRegression()
lr.fit(X_train_imputed,y_train)
y_pred = lr.predict(X_test_imputed)
accuracy_score(y_test,y_pred)

0.6424581005586593

In [8]:
knn = KNNImputer(n_neighbors=2,weights='distance')
X_train_imputed  = knn.fit_transform(X_train)
X_test_imputed = knn.transform(X_test)

In [9]:
lr = LogisticRegression()
lr.fit(X_train_imputed,y_train)
y_pred = lr.predict(X_test_imputed)
accuracy_score(y_test,y_pred)

0.659217877094972